try:
    print(num)
except NameError:
    print('产生错误了')